// <auto-generated />
using Laboratoire4Prog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Laboratoire4Prog.Migrations
{
    [DbContext(typeof(Laboratoire4ProgContext))]
    [Migration("20200516210156_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Laboratoire4Prog.Models.Tetes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Comment");

                    b.Property<string>("Descript");

                    b.Property<DateTime>("HeureTete");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Tetes");
                });
#pragma warning restore 612, 618
        }
    }
}
